In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.externals import joblib

In [2]:
df = pd.read_csv('house_price.csv')
df

area   price
0  3000   56500
1  2600   55000
2  4000   72000
3  5400   98000
4  6000  120000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
model.coef_

array([18.73853211])

In [5]:
model.intercept_

1598.165137614662

In [6]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [7]:
mj = joblib.load('model_joblib')

In [8]:
mj.predict([[5000]])

array([95290.82568807])

In [9]:
mj.coef_

array([18.73853211])