In [1]:
# 1. Import numpy library
import numpy as np

In [2]:
# 2. print numpy version
print(np.__version__)

1.18.1


In [3]:
# 3. Create a null vector of size 10
arry = np.zeros(10)
print(arry)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 4. Create a null vector of size 10 but the fifth value which is 1
arry = np.zeros(10)
arry[4] = 1
print(arry)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
# 5. Create a vector with values ranging from 10 to 49
arry = np.arange(10,50)
print(arry)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# 6. Reverse a vector (first element becomes last)
arry = arry[::-1]
print(arry)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 8. Find indices of non­zero elements from [1,2,0,0,4,0]
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


In [10]:
# 9. Create a 3x3 identity matrix
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 11. Create a 3x3x3 array with random values
print(np.random.random((3,3,3)))

[[[0.25753129 0.98275599 0.2521914 ]
  [0.54052917 0.3415014  0.46529496]
  [0.76234464 0.42288417 0.28897642]]

 [[0.03147016 0.36993218 0.25871069]
  [0.17866461 0.06685515 0.22657354]
  [0.39174793 0.1895266  0.68766351]]

 [[0.35576418 0.09659706 0.42921473]
  [0.23535937 0.82947971 0.26988247]
  [0.23086365 0.07712412 0.39204162]]]


In [20]:
# 12. Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
print(Z.min(), Z.max())

0.02991843316245757 0.9635150719298464


In [22]:
# 13. Create a random vector of size 30 and find the mean value
Z = np.random.random((30))
print(Z.mean())

0.5010298345595514


In [23]:
# 14. Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
# 15. nan functionality
print(np.nan)
print( 0 * np.nan)
print( np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
nan
False
False
nan
False


In [28]:
# 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [44]:
print(np.diag(1+np.arange(4), k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [45]:
# 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
