In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math

In [4]:
'''
Features => these are called independent variable
outcome => called dependent variable
'''

'\nFeatures => these are called independent variable\noutcome => called dependent variable\n'

In [5]:
df = pd.read_csv('pricing.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
median_beroom = math.floor(df.bedrooms.median())
median_beroom

3

In [7]:
df.bedrooms = df.bedrooms.fillna(median_beroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.9999999998

In [11]:
# Predict the price
reg.predict([[3000, 3, 40]])

array([444400.])

In [12]:
# Explain how we got the prediction value
137.25 * 3000 + -26025 * 3 + -6825 * 40 + 383724.9999999998

444399.9999999998

In [13]:
# Predict the price
reg.predict([[2500, 4, 5]])

array([588625.])